### ISSUE TITLE
buffers without spaces

### ISSUE THREAD

**Issue by juliangruber** [dominictarr/json-buffer#1]
You check if something is a buffer by testing it for `/==$/`. The problem is that `new Buffer('foo').toString('base64') == 'Zm9v'`.

The dirty way would be to add whitespace to serialized buffers and remove that afterwards. But if we already do that we could also just replace them with `{ _buffer : "Zm9v" }`.

**Comment by timmfin** [comment]
I think this can be closed?

```
> new Buffer('foo')
<Buffer 66 6f 6f>
> JSONB.parse(JSONB.stringify(new Buffer('foo')))
<Buffer 66 6f 6f>
> new Buffer(' foo')
<Buffer 20 66 6f 6f>
> JSONB.parse(JSONB.stringify(new Buffer(' foo')))
<Buffer 20 66 6f 6f>
```
