### ISSUE TITLE
Incorrect handling of `undefined`

### ISSUE THREAD

**Issue by lukechilds** [dominictarr/json-buffer#7]
The core `JSON.stringify` method outputs `undefined` as `undefined`. `json-buffer` outputs `'null'`.

e.g:

```js
const JSONB = require('json-buffer');

JSON.stringify(undefined);
// undefined
JSONB.stringify(undefined);
// 'null'
```

**Comment by dominictarr** [comment]
aha, but there is a special case in arrays, where `[,,,1]` becomes `[null,null,null, 1]`

fixed in 3.0.0
made it a breaking change because maybe there was some stuff that depended on this (wrong) behavior,
but new code will get the correct thing.

**Comment by lukechilds** [comment]
Wow, that was fast!

I was half way through, you beat me to it. Want my test? https://github.com/dominictarr/json-buffer/pull/8

**Comment by dominictarr** [comment]
haha, you just got lucky - or maybe your issue title didn't sound like a big deal.
I added a test that covered that case, but thanks anyway!
