### ISSUE TITLE
Replacing calls to the Buffer constructor with Buffer.from(...)

### ISSUE THREAD

**Issue by gabrielschulhof** [dominictarr/json-buffer#9]
`new Buffer(...)` is deprecated and unsafe. Would it be possible to replace [its usage](https://github.com/dominictarr/json-buffer/search?q=%22new+Buffer%22&unscoped_q=%22new+Buffer%22) with `Buffer.from(...)`?

**Comment by dominictarr** [comment]
would merge a PR
